create table if not exists cursos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  modalidad text not null check (modalidad in ('presencial', 'online')),
  horas integer not null check (horas > 0),
  created_at timestamptz not null default now()
);

alter table cursos
add column if not exists updated_at timestamptz;

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists cursos_set_updated_at on cursos;

create trigger cursos_set_updated_at
before update on cursos
for each row
execute function set_updated_at();

-- Comprobacion para el SQL Editor:
-- Inserta un curso, actualiza su nombre y devuelve updated_at ya rellenado.
with curso_demo as (
  insert into cursos (nombre, modalidad, horas)
  values ('Curso de prueba', 'online', 12)
  returning id
)
update cursos
set nombre = 'Curso de prueba actualizado'
from curso_demo
where cursos.id = curso_demo.id
returning cursos.id, cursos.nombre, cursos.updated_at;
