-- 1. Creamos la tabla cursos si aun no existe.
-- id se genera automaticamente.
-- created_at guarda la fecha de creacion automaticamente con now().
create table if not exists cursos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  modalidad text not null check (modalidad in ('presencial', 'online')),
  horas integer not null check (horas > 0),
  created_at timestamptz not null default now()
);

-- 2. Anade la columna updated_at si no existe.
-- Esta columna guardara la ultima vez que se modifico cada curso.
alter table cursos
add column if not exists updated_at timestamptz;

-- 3. Creamos la funcion que usara el trigger.
-- NEW representa la fila nueva/modificada antes de guardarse.
-- Ponemos new.updated_at = now() para guardar la fecha actual.
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 4. Borramos el trigger anterior si ya existia.
-- Esto evita errores si ejecutamos el SQL mas de una vez.
drop trigger if exists cursos_set_updated_at on cursos;

-- 5. Creamos el trigger.
-- BEFORE UPDATE significa que se ejecuta antes de actualizar una fila.
-- FOR EACH ROW significa que se ejecuta por cada curso modificado.
create trigger cursos_set_updated_at
before update on cursos
for each row
execute function set_updated_at();
